package com.MyBatis_MBG.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.d_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.d_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.d_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private Integer dSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.d_id
     *
     * @return the value of dept.d_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.d_id
     *
     * @param dId the value for dept.d_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.d_name
     *
     * @return the value of dept.d_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.d_name
     *
     * @param dName the value for dept.d_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.d_sex
     *
     * @return the value of dept.d_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public Integer getdSex() {
        return dSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.d_sex
     *
     * @param dSex the value for dept.d_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void setdSex(Integer dSex) {
        this.dSex = dSex;
    }
}