package com.MyBatis_MBG.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private Integer eSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_depart
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private Integer eDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_email
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    private String eEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_id
     *
     * @return the value of emp.e_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_id
     *
     * @param eId the value for emp.e_id
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_name
     *
     * @return the value of emp.e_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_name
     *
     * @param eName the value for emp.e_name
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_sex
     *
     * @return the value of emp.e_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public Integer geteSex() {
        return eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_sex
     *
     * @param eSex the value for emp.e_sex
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void seteSex(Integer eSex) {
        this.eSex = eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_depart
     *
     * @return the value of emp.e_depart
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public Integer geteDepart() {
        return eDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_depart
     *
     * @param eDepart the value for emp.e_depart
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void seteDepart(Integer eDepart) {
        this.eDepart = eDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_email
     *
     * @return the value of emp.e_email
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public String geteEmail() {
        return eEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_email
     *
     * @param eEmail the value for emp.e_email
     *
     * @mbggenerated Sat May 28 10:47:48 CST 2022
     */
    public void seteEmail(String eEmail) {
        this.eEmail = eEmail == null ? null : eEmail.trim();
    }


    public Emp() {

    }

    public Emp(Integer eId, String eName, Integer eSex, Integer eDepart, String eEmail) {
        this.eId = eId;
        this.eName = eName;
        this.eSex = eSex;
        this.eDepart = eDepart;
        this.eEmail = eEmail;
    }

    //    tostring
    @Override
    public String toString() {
        return "Emp{" +
                "eId=" + eId +
                ", eName='" + eName + '\'' +
                ", eSex=" + eSex +
                ", eDepart=" + eDepart +
                ", eEmail='" + eEmail + '\'' +
                '}';
    }
}